### PR TITLE
add_reversed_number

### PR DESCRIPTION
**Pull request by 17bcs029**
It is a question of spoj add reversed number.

### CODE REVIEW

**Comment by knakul853** [comment]
hey @17bcs029  try to comment where needed.
there is to much same comment for same logic

**Comment by 17bcs029** [comment]
Sorry  there will be no so much mistake in future.

**Comment by knakul853** [comment]
@17bcs029  no sorry bro chill

**Comment by 17bcs029** [comment]
okay bro thankyou for suggestion.

**Pull request merged**
